services:
  backend:
    build: ./api/.
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: sync
          path: ./api/.
          target: /home/node/app
  frontend:
    build: ./client
    ports:
      - "3001:3000"
    develop:
      watch:
        - action: sync
          path: ./client
          target: /home/node/app
