services:
  backend:
    build: ./api/.
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: sync+restart
          path: ./api/.
          target: /home/node/app
        - action: rebuild
          path: ./api/package.json
          target: /home/node/app/package.json
    env_file:
      - ./api/pwse_api.env
  frontend:
    build: ./client
    ports:
      - "5005:5005"
    develop:
      watch:
        - action: sync+restart
          path: ./client
          target: /home/node/app
        - action: rebuild
          path: ./client/package.json
          target: /home/node/app/package.json
    env_file:
      - ./client/pwse_client.env